spring:
  mail:
#    host: smtp-relay.sendinblue.com
#    username: chandanhp49@gmail.com
#    password: jzIEyV0J7c26sfLv
#    port: 587

    host: smtp-relay.sendinblue.com
    username: maheshsmugali@gmail.com
    password: NbQZcKLJIqfng5TB
    port: 587

